In [3]:
import numpy as np


In [4]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
np.zeros(2)
np.zeros((4,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np.linspace(1,8,10)

array([1.        , 1.77777778, 2.55555556, 3.33333333, 4.11111111,
       4.88888889, 5.66666667, 6.44444444, 7.22222222, 8.        ])

Random Generation Function

In [11]:
np.random.rand(5)

array([0.90011993, 0.29037751, 0.823962  , 0.94214921, 0.9142964 ])

In [12]:
np.random.randn(10)

array([ 0.07196427, -0.10784236, -0.10126843,  2.06109194,  0.57241093,
        0.13006886, -0.525054  ,  0.20083078,  0.41058958,  0.61628114])

In [13]:
np.random.randint(10,30,8)

array([27, 22, 12, 16, 29, 11, 23, 25], dtype=int32)

Array attribute

In [14]:
ar=np.array(l)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
ar.shape

(3, 3)

In [16]:
ar.size

9

In [17]:
ar.dtype

dtype('int64')

Array methods

In [18]:
ar.min()

np.int64(1)

In [19]:
ar.max()

np.int64(9)

In [20]:
ar.sum()

np.int64(45)

In [21]:
np.sum(ar,axis=1)

array([ 6, 15, 24])

In [22]:
ar.mean()

np.float64(5.0)

In [23]:
ar.std()

np.float64(2.581988897471611)

In [24]:
ar.argmax()

np.int64(8)

In [25]:
ar.argmin()

np.int64(0)

Reshaping and resizing

In [26]:
arr=np.arange(1,31)

In [27]:
arr.reshape((6,5))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Indexing and slicing

In [28]:
arr=np.arange(11,21)

In [29]:
arr[1:5]

array([12, 13, 14, 15])

In [30]:
arr[1:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [31]:
arr[:5]

array([11, 12, 13, 14, 15])

In [32]:
arr[1::2]

array([12, 14, 16, 18, 20])

In matrix

In [33]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [34]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [35]:
arr[2:5,1:4]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

Boolean Indexing

In [36]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [37]:
bool_index=arr%2==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [38]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

Array operations

1. Arithmetic operation


In [39]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [40]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [41]:
a1-a2

array([-5, -5, -5, -5, -5])

In [42]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [43]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [44]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [45]:
a1%a2

array([1, 2, 3, 4, 5])

2. Broadcasting

In [46]:
l=[10,20,30,40,50]
arr=np.array(l)
arr

array([10, 20, 30, 40, 50])

In [47]:
arr*10

array([100, 200, 300, 400, 500])

Matrix operation


In [49]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [51]:
A*B

array([[ 5, 12],
       [21, 32]])

In [53]:
A@B #matrix-multiplication

array([[19, 22],
       [43, 50]])

In [55]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [ ]:
A.T #Transpose of the matrix

array([[1, 3],
       [2, 4]])

Advance array manipulation

1. Stacking of the array

In [63]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [65]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [72]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

2. Array Spliting

In [75]:
c=np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [80]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [82]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [83]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]